[project]
name = "mcp-crew"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.15.20",
    "crewai-tools[mcp]>=1.15.20",
    "langchain-openai>=1.6.1",
    "python-dotenv>=1.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
